FROM node:21 as build

LABEL description="bugtrap-app"
LABEL version="1.0.0"

ENV HOME=/usr/src/app
WORKDIR ${HOME}

COPY ./apps/api/ ${HOME}/bugtrap/

WORKDIR ${HOME}/bugtrap

RUN pnpm config set global-bin-dir /usr/local/bin

RUN corepack enable && pnpm install --no-frozen-lockfile && pnpm add @nestjs/cli --save-dev

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
