FROM node:21 as build

LABEL description="bugtrap-app"
LABEL version="1.0.0"

ENV HOME=/usr/src/app

WORKDIR ${HOME}

COPY ./apps/api/ ${HOME}/bugtrap/
WORKDIR ${HOME}/bugtrap

RUN npm install --frozen-lockfile && npm install --save-dev @nestjs/cli

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
